server:
  tomcat:
    max-http-form-post-size: 500MB
  servlet:
    contextPath: /api

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false

    properties:
      hibernate:
        default_batch_fetch_size: 500
#        format_sql: true
#        show-sql: true
        open-in-view: false

  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 150MB

jwt:
  token:
    secret-key: "hello"
    expTime: 2592000
    issuer: "dohee"

#logging:
#  level:
#    org.hibernate.SQL: debug