spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false

    properties:
      hibernate:
        default_batch_fetch_size: 500
#        format_sql: true
#        show-sql: true
        open-in-view: false

jwt:
  token:
    secret-key: "hello"
    expTime: 1800000
    issuer: "dohee"

#logging:
#  level:
#    org.hibernate.SQL: debug